// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIEdg4KWxGYACLRxTIUjlD5bhVyHXHiCE',
    appId: '1:876632381056:web:fa7897bc2fbf293294b865',
    messagingSenderId: '876632381056',
    projectId: 'namma-ooru-nearu-373605',
    authDomain: 'namma-ooru-nearu-373605.firebaseapp.com',
    storageBucket: 'namma-ooru-nearu-373605.appspot.com',
    measurementId: 'G-78GR23QEWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNB0sZGAxZYWS3yBRlq6KFqhnXugk2KAY',
    appId: '1:876632381056:android:92c0db186eb3adbf94b865',
    messagingSenderId: '876632381056',
    projectId: 'namma-ooru-nearu-373605',
    storageBucket: 'namma-ooru-nearu-373605.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYDCQ06FGRjyBIk_tztC_GH7yEmrOZOBE',
    appId: '1:876632381056:ios:aa70dbc8a6e0a3bc94b865',
    messagingSenderId: '876632381056',
    projectId: 'namma-ooru-nearu-373605',
    storageBucket: 'namma-ooru-nearu-373605.appspot.com',
    iosClientId: '876632381056-m0j18nfl8doel72ankkapde139f9a9ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.nammaooruNearu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYDCQ06FGRjyBIk_tztC_GH7yEmrOZOBE',
    appId: '1:876632381056:ios:aa70dbc8a6e0a3bc94b865',
    messagingSenderId: '876632381056',
    projectId: 'namma-ooru-nearu-373605',
    storageBucket: 'namma-ooru-nearu-373605.appspot.com',
    iosClientId: '876632381056-m0j18nfl8doel72ankkapde139f9a9ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.nammaooruNearu',
  );
}
