on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.8'
      - run: flutter pub get
      - run: flutter build apk 
      # -run: |
      #     cd ios
      #     rm podfile.lock
      #     pod deintegrate
      #     pod repo update
      #     pod install
      # - run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "build/app/output/release/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.APP_TOKEN}}
      - name: upload artifacts to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:         
          appId: ${{secrets.FIREBASE_ANDROID_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: build/app/outputs/apk/release/app-release.apk
      # - name: Push to Release
      #   uses: ncipollo/release-action@v1
      #   with:
         

      #     artifacts:
      #     "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
      #     tag: v1.0.${{ github.run_number}}    
      #     token: %{{secrets.TOKEN}}